apiVersion: v1
kind: Service
metadata:
  name: myonlineapp-svc
  labels:
    app: myonlineapp
    version: 2.1.1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: myonlineapp
    version: 2.1.1